### ISSUE TITLE
Error in get_watch_price_data

### ISSUE THREAD

**Issue by rahnama7m** [mahs4d/tsetmc-api#10] opened 2023-05-23 06:52 UTC
These codes: 
```
from tsetmc_api import market_watch
market_watch_instance = market_watch.MarketWatch()
data =market_watch_instance.get_price_data()
```
will raise error: 
```
rows = sections[2].split(';')
IndexError: list index out of range
```
in `get_watch_price_data` function that get MarketWatchPlus data .

**Comment by milad-mr** [comment] 2023-05-26 21:27
This error might be caused by change in tsetmc website.
 You can change tsetmc.com to old.tsetmc.com in _core files and check if it work.

**Comment by mahs4d** [comment] 2023-05-27 16:24
As @milad-mr mentioned, the problem is that `tsetmc` has changed its base URLs.

This issue should be fixed in version `5.0.5`.
Please let me know if there are any other problems. 

Thanks :pray:

**Closed as completed** 2023-05-27 16:25 UTC
